// src/routes/dashboard.tsx
import { createFileRoute, Navigate, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import {
  Bell, ChevronDown, FileText, Settings as SettingsIcon, CheckCircle2, Clock, Plus, Search, LogOut, User as UserIcon,
  Workflow, LayoutTemplate, Upload, Star, List, LayoutGrid,
} from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/lib/auth-context";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/dashboard")({
  head: () => ({ meta: [{ title: "Dashboard — Jabil Forms" }] }),
  component: DashboardPage,
});

const TABS = ["Recent", "My forms", "Filled forms", "Shared with me", "Favorites"] as const;

const TEMPLATES = [
  { title: "Workflow Solution", desc: "Streamline your work flow: collect info, send reminders, view summaries. All set!", gradient: "from-[#6366f1] to-[#8b5cf6]" },
  { title: "Registration", desc: "Event sign-ups, training enrollment, visitor check-in.", gradient: "from-[#f97316] to-[#fb923c]" },
  { title: "Research", desc: "Surveys, feedback collection, market research.", gradient: "from-[#3b82f6] to-[#60a5fa]" },
  { title: "Quiz", desc: "Knowledge checks, certifications, compliance tests.", gradient: "from-[#ec4899] to-[#f472b6]" },
];

const FORMS = [
  { id: 1, name: "Equipment Calibration Log #4421", by: "Maria Chen", date: "Today, 09:42", status: "Pending" as const, responses: 12 },
  { id: 2, name: "Quality Inspection — Line 3", by: "David Patel", date: "Today, 08:15", status: "Approved" as const, responses: 34 },
  { id: 3, name: "Material Variance Report", by: "Aisha Okafor", date: "Yesterday, 17:22", status: "Approved" as const, responses: 8 },
  { id: 4, name: "Safety Incident — Bay 12", by: "Tomás Rivera", date: "Yesterday, 14:08", status: "Rejected" as const, responses: 1 },
  { id: 5, name: "Shift Handover — Night Crew", by: "Lin Wei", date: "Jun 10, 23:05", status: "Approved" as const, responses: 5 },
  { id: 6, name: "Supplier Audit Checklist", by: "Rachel Kim", date: "Jun 9, 16:30", status: "Pending" as const, responses: 0 },
];

function DashboardPage() {
  const { user, isAuthenticated, signOut } = useAuth();
  const navigate = useNavigate();
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeTab, setActiveTab] = useState<typeof TABS[number]>("Recent");
  const [viewMode, setViewMode] = useState<"grid" | "list">("grid");
  const [searchQuery, setSearchQuery] = useState("");

  if (!isAuthenticated || !user) return <Navigate to="/signin" replace />;

  const handleSignOut = () => {
    signOut();
    toast.success("Signed out");
    navigate({ to: "/signin" });
  };

  const firstName = user.name.split(" ")[0];
  const greeting = (() => {
    const h = new Date().getHours();
    if (h < 12) return "Good morning";
    if (h < 18) return "Good afternoon";
    return "Good evening";
  })();
  const today = new Date().toLocaleDateString(undefined, {
    weekday: "long", month: "long", day: "numeric", year: "numeric",
  });

  const filteredForms = FORMS.filter(f =>
    f.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    f.by.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="flex min-h-dvh flex-col bg-background">
      {/* TOP NAVBAR */}
      <header className="sticky top-0 z-30 flex h-16 items-center gap-4 border-b border-border bg-card px-4 lg:px-6">
        <div className="flex items-center gap-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-md bg-primary">
            <FileText className="h-4 w-4 text-primary-foreground" />
          </div>
          <span className="hidden text-sm font-bold tracking-tight sm:inline">
            Jabil Forms
          </span>
        </div>

        <nav className="ml-6 hidden items-center gap-1 md:flex">
          {["Dashboard", "My Forms", "Templates", "Reports"].map((n, i) => (
            <button
              key={n}
              onClick={() => i > 0 && toast.info(`${n} coming soon`)}
              className={`rounded-md px-3 py-2 text-sm font-medium transition-colors ${
                i === 0 ? "bg-secondary text-foreground" : "text-muted-foreground hover:bg-secondary hover:text-foreground"
              }`}
            >
              {n}
            </button>
          ))}
        </nav>

        <div className="ml-auto flex items-center gap-1">
          <button
            aria-label="Notifications"
            onClick={() => toast.info("No new notifications")}
            className="relative rounded-md p-2 hover:bg-secondary"
          >
            <Bell className="h-5 w-5" />
            <span className="absolute right-1.5 top-1.5 h-2 w-2 rounded-full bg-accent" />
          </button>

          <div className="relative">
            <button
              onClick={() => setMenuOpen((o) => !o)}
              className="flex items-center gap-2 rounded-md p-1.5 hover:bg-secondary"
              aria-haspopup="menu"
              aria-expanded={menuOpen}
            >
              <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">
                {user.name.split(" ").map((s) => s[0]).slice(0, 2).join("")}
              </div>
              <ChevronDown className="hidden h-4 w-4 text-muted-foreground sm:inline" />
            </button>
            {menuOpen && (
              <div
                role="menu"
                className="animate-fade-in absolute right-0 mt-2 w-56 overflow-hidden rounded-md border border-border bg-popover shadow-lg"
                onMouseLeave={() => setMenuOpen(false)}
              >
                <div className="border-b border-border px-3 py-2.5">
                  <p className="text-sm font-medium">{user.name}</p>
                  <p className="truncate text-xs text-muted-foreground">{user.email}</p>
                </div>
                <MenuItem icon={UserIcon} label="Profile" onClick={() => toast.info("Profile")} />
                <MenuItem icon={SettingsIcon} label="Settings" onClick={() => toast.info("Settings")} />
                <div className="border-t border-border" />
                <MenuItem icon={LogOut} label="Sign Out" onClick={handleSignOut} destructive />
              </div>
            )}
          </div>
        </div>
      </header>

      {/* MAIN */}
      <main className="flex-1 overflow-x-auto px-4 py-6 lg:px-8">
        <div className="mx-auto max-w-7xl">

          {/* 1. Greeting */}
          <div className="mb-6">
            <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">
              {greeting}, {firstName}
            </h1>
            <p className="mt-1 text-sm text-muted-foreground">{today}</p>
          </div>

          {/* 2. Action Buttons */}
          <div className="flex flex-wrap items-center gap-3">
            <Button onClick={() => toast.success("New form created")}>
              <Plus className="h-4 w-4 mr-1.5" /> New Form
            </Button>
            <Button variant="outline" onClick={() => toast.success("New quiz created")}>
              <LayoutTemplate className="h-4 w-4 mr-1.5" /> New Quiz
            </Button>
            <Button variant="outline" onClick={() => toast.info("Import feature coming soon")}>
              <Upload className="h-4 w-4 mr-1.5" /> Quick import
            </Button>
          </div>

          {/* 3. Templates */}
          <section className="mt-8">
            <h2 className="mb-4 text-base font-semibold text-foreground">Explore templates</h2>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
              {TEMPLATES.map((t) => (
                <button
                  key={t.title}
                  onClick={() => toast.info(`Template "${t.title}" selected`)}
                  className={`relative overflow-hidden rounded-xl bg-gradient-to-br ${t.gradient} p-5 text-left text-white shadow-sm transition-transform hover:-translate-y-0.5 hover:shadow-md`}
                >
                  <div className="relative z-10">
                    <p className="text-sm font-semibold">{t.title}</p>
                    <p className="mt-1 text-xs leading-relaxed opacity-90">{t.desc}</p>
                  </div>
                  {/* Decorative circle */}
                  <div className="absolute -bottom-4 -right-4 h-24 w-24 rounded-full bg-white/10" />
                </button>
              ))}
            </div>
          </section>

          {/* 4. Stats */}
          <div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <StatCard icon={FileText} label="Total Forms" value="248" tint="bg-primary/10 text-primary" />
            <StatCard icon={Clock} label="Pending Approvals" value="12" tint="bg-amber-500/10 text-amber-600" />
            <StatCard icon={CheckCircle2} label="Submitted Today" value="34" tint="bg-success/10 text-success" />
            <StatCard icon={Workflow} label="Active Workflows" value="7" tint="bg-accent/10 text-accent" />
          </div>

          {/* 5. Tabs + Search */}
          <div className="mt-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex items-center gap-1 overflow-x-auto">
              {TABS.map((tab) => (
                <button
                  key={tab}
                  onClick={() => {
                    setActiveTab(tab);
                    if (tab !== "Recent") toast.info(`${tab} view coming soon`);
                  }}
                  className={`relative whitespace-nowrap rounded-md px-3 py-2 text-sm font-medium transition-colors ${
                    activeTab === tab
                      ? "text-foreground"
                      : "text-muted-foreground hover:bg-secondary hover:text-foreground"
                  }`}
                >
                  {tab === "Favorites" && <Star className="mr-1 inline h-3.5 w-3.5" />}
                  {tab}
                  {activeTab === tab && (
                    <span className="absolute bottom-0 left-3 right-3 h-0.5 rounded-full bg-primary" />
                  )}
                </button>
              ))}
            </div>

            <div className="flex items-center gap-2">
              <div className="relative">
                <Search className="pointer-events-none absolute left-2.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <input
                  placeholder="Filter by keyword"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="h-9 w-56 rounded-md border border-input bg-background pl-8 pr-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"
                />
              </div>
              <button
                onClick={() => setViewMode("list")}
                className={`rounded-md p-2 ${viewMode === "list" ? "bg-secondary text-foreground" : "text-muted-foreground hover:bg-secondary"}`}
                aria-label="List view"
              >
                <List className="h-4 w-4" />
              </button>
              <button
                onClick={() => setViewMode("grid")}
                className={`rounded-md p-2 ${viewMode === "grid" ? "bg-secondary text-foreground" : "text-muted-foreground hover:bg-secondary"}`}
                aria-label="Grid view"
              >
                <LayoutGrid className="h-4 w-4" />
              </button>
            </div>
          </div>

          {/* 6. Forms Grid / List */}
          <section className="mt-4">
            {viewMode === "grid" ? (
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {filteredForms.map((form) => (
                  <FormCard key={form.id} form={form} />
                ))}
              </div>
            ) : (
              <div className="overflow-hidden rounded-xl border border-border bg-card">
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead className="bg-secondary/50 text-xs uppercase tracking-wide text-muted-foreground">
                      <tr>
                        <th className="px-5 py-3 text-left font-medium">Form Name</th>
                        <th className="px-5 py-3 text-left font-medium">Submitted By</th>
                        <th className="px-5 py-3 text-left font-medium">Date</th>
                        <th className="px-5 py-3 text-left font-medium">Status</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-border">
                      {filteredForms.map((r) => (
                        <tr key={r.id} className="transition-colors hover:bg-secondary/40">
                          <td className="px-5 py-3.5 font-medium">{r.name}</td>
                          <td className="px-5 py-3.5 text-muted-foreground">{r.by}</td>
                          <td className="px-5 py-3.5 text-muted-foreground">{r.date}</td>
                          <td className="px-5 py-3.5"><StatusBadge status={r.status} /></td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </section>

        </div>
      </main>
    </div>
  );
}

function MenuItem({
  icon: Icon, label, onClick, destructive,
}: { icon: React.ComponentType<{ className?: string }>; label: string; onClick: () => void; destructive?: boolean }) {
  return (
    <button
      role="menuitem"
      onClick={onClick}
      className={`flex w-full items-center gap-2.5 px-3 py-2 text-sm transition-colors hover:bg-secondary ${
        destructive ? "text-destructive" : "text-foreground"
      }`}
    >
      <Icon className="h-4 w-4" />
      {label}
    </button>
  );
}

function StatCard({
  icon: Icon, label, value, tint,
}: { icon: React.ComponentType<{ className?: string }>; label: string; value: string; tint: string }) {
  return (
    <div className="rounded-xl border border-border bg-card p-5 transition-shadow hover:shadow-sm">
      <div className="flex items-center justify-between">
        <span className="text-sm text-muted-foreground">{label}</span>
        <div className={`flex h-9 w-9 items-center justify-center rounded-lg ${tint}`}>
          <Icon className="h-4 w-4" />
        </div>
      </div>
      <p className="mt-3 text-3xl font-bold tracking-tight">{value}</p>
    </div>
  );
}

function StatusBadge({ status }: { status: "Pending" | "Approved" | "Rejected" }) {
  const styles = {
    Pending: "bg-amber-500/10 text-amber-700 ring-amber-500/20",
    Approved: "bg-success/10 text-success ring-success/20",
    Rejected: "bg-destructive/10 text-destructive ring-destructive/20",
  } as const;
  return (
    <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ring-1 ring-inset ${styles[status]}`}>
      {status}
    </span>
  );
}

function FormCard({ form }: { form: typeof FORMS[number] }) {
  const statusColors = {
    Pending: "bg-amber-500",
    Approved: "bg-success",
    Rejected: "bg-destructive",
  } as const;

  return (
    <button
      onClick={() => toast.info(`Opening "${form.name}"`)}
      className="rounded-xl border border-border bg-card p-0 text-left transition-shadow hover:shadow-sm overflow-hidden"
    >
      {/* Thumbnail area */}
      <div className="relative h-28 bg-secondary/60 flex items-center justify-center">
        <FileText className="h-10 w-10 text-muted-foreground/40" />
        <span className={`absolute top-3 right-3 h-2.5 w-2.5 rounded-full ${statusColors[form.status]}`} />
      </div>
      <div className="p-4">
        <p className="text-sm font-semibold line-clamp-2">{form.name}</p>
        <p className="mt-1 text-xs text-muted-foreground">{form.by}</p>
        <div className="mt-3 flex items-center justify-between">
          <span className="text-xs text-muted-foreground">{form.date}</span>
          <span className="text-xs font-medium text-muted-foreground">{form.responses} responses</span>
        </div>
      </div>
    </button>
  );
}

// frontend/src/app/pages/dashboard/dashboard.component.ts
import { Component, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { MatMenuModule } from '@angular/material/menu';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { AuthService } from '../../core/services/auth.service';

export interface FormItem {
  id: number;
  name: string;
  by: string;
  date: string;
  status: 'Pending' | 'Approved' | 'Rejected';
  responses: number;
}

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatMenuModule,
    MatButtonModule,
    MatIconModule,
    MatSnackBarModule,
  ],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.scss',
})
export class DashboardComponent {
  readonly TABS = ['Recent', 'My forms', 'Filled forms', 'Shared with me', 'Favorites'] as const;

  readonly TEMPLATES = [
    {
      title: 'Workflow Solution',
      desc: 'Streamline your workflow: collect info, send reminders, view summaries. All set!',
      gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    },
    {
      title: 'Registration',
      desc: 'Event sign-ups, training enrollment, visitor check-in.',
      gradient: 'linear-gradient(135deg, #f97316, #fb923c)',
    },
    {
      title: 'Research',
      desc: 'Surveys, feedback collection, market research.',
      gradient: 'linear-gradient(135deg, #3b82f6, #60a5fa)',
    },
    {
      title: 'Quiz',
      desc: 'Knowledge checks, certifications, compliance tests.',
      gradient: 'linear-gradient(135deg, #ec4899, #f472b6)',
    },
  ];

  readonly FORMS: FormItem[] = [
    { id: 1, name: 'Equipment Calibration Log #4421', by: 'Maria Chen', date: 'Today, 09:42', status: 'Pending', responses: 12 },
    { id: 2, name: 'Quality Inspection — Line 3', by: 'David Patel', date: 'Today, 08:15', status: 'Approved', responses: 34 },
    { id: 3, name: 'Material Variance Report', by: 'Aisha Okafor', date: 'Yesterday, 17:22', status: 'Approved', responses: 8 },
    { id: 4, name: 'Safety Incident — Bay 12', by: 'Tomás Rivera', date: 'Yesterday, 14:08', status: 'Rejected', responses: 1 },
    { id: 5, name: 'Shift Handover — Night Crew', by: 'Lin Wei', date: 'Jun 10, 23:05', status: 'Approved', responses: 5 },
    { id: 6, name: 'Supplier Audit Checklist', by: 'Rachel Kim', date: 'Jun 9, 16:30', status: 'Pending', responses: 0 },
  ];

  activeTab = signal<string>('Recent');
  viewMode = signal<'grid' | 'list'>('grid');
  searchQuery = signal<string>('');

  constructor(
    readonly auth: AuthService,
    private router: Router,
    private snackBar: MatSnackBar
  ) {}

  get userInitials(): string {
    const u = this.auth.user();
    if (!u) return '';
    return u.name
      .split(' ')
      .map((s) => s[0])
      .slice(0, 2)
      .join('')
      .toUpperCase();
  }

  get firstName(): string {
    const u = this.auth.user();
    if (!u) return '';
    return u.name.split(' ')[0];
  }

  get greeting(): string {
    const h = new Date().getHours();
    if (h < 12) return 'Good morning';
    if (h < 18) return 'Good afternoon';
    return 'Good evening';
  }

  get todayFormatted(): string {
    return new Date().toLocaleDateString(undefined, {
      weekday: 'long',
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    });
  }

  get filteredForms(): FormItem[] {
    const query = this.searchQuery().toLowerCase().trim();
    if (!query) return this.FORMS;
    return this.FORMS.filter(
      (f) =>
        f.name.toLowerCase().includes(query) ||
        f.by.toLowerCase().includes(query)
    );
  }

  onTabChange(tab: string): void {
    this.activeTab.set(tab);
    if (tab !== 'Recent') {
      this.snackBar.open(`${tab} view coming soon`, 'Close', { duration: 2500 });
    }
  }

  onTemplateClick(title: string): void {
    this.snackBar.open(`Template "${title}" selected`, 'Close', { duration: 2500 });
  }

  onNavClick(item: string): void {
    if (item !== 'Dashboard') {
      this.snackBar.open(`${item} coming soon`, 'Close', { duration: 2500 });
    }
  }

  onCreateForm(): void {
    this.snackBar.open('New form created', 'Close', { duration: 2500 });
  }

  onCreateQuiz(): void {
    this.snackBar.open('New quiz created', 'Close', { duration: 2500 });
  }

  onImport(): void {
    this.snackBar.open('Import feature coming soon', 'Close', { duration: 2500 });
  }

  onNotificationClick(): void {
    this.snackBar.open('No new notifications', 'Close', { duration: 2500 });
  }

  onProfileClick(): void {
    this.snackBar.open('Profile coming soon', 'Close', { duration: 2500 });
  }

  onSettingsClick(): void {
    this.snackBar.open('Settings coming soon', 'Close', { duration: 2500 });
  }

  onFormClick(name: string): void {
    this.snackBar.open(`Opening "${name}"`, 'Close', { duration: 2500 });
  }

  signOut(): void {
    this.auth.signOut();
    this.snackBar.open('Signed out', 'Close', { duration: 3000 });
    this.router.navigate(['/signin']);
  }
}

<div class="dashboard-wrapper">
  <!-- TOP NAVBAR -->
  <header class="navbar">
    <div class="navbar-left">
      <div class="logo-container">
        <mat-icon class="logo-icon">description</mat-icon>
      </div>
      <span class="logo-text">Jabil Forms</span>

      <nav class="navbar-nav">
        @for (item of ['Dashboard', 'My Forms', 'Templates', 'Reports']; track item; let idx = $index) {
          <button
            (click)="onNavClick(item)"
            class="nav-btn"
            [class.active]="idx === 0"
          >
            {{ item }}
          </button>
        }
      </nav>
    </div>

    <div class="navbar-right">
      <button
        aria-label="Notifications"
        (click)="onNotificationClick()"
        class="icon-btn"
      >
        <mat-icon>notifications</mat-icon>
        <span class="notification-badge"></span>
      </button>

      <div class="profile-menu-container">
        <button [matMenuTriggerFor]="profileMenu" class="profile-trigger">
          <div class="avatar-circle">
            {{ userInitials }}
          </div>
          <mat-icon class="dropdown-chevron">keyboard_arrow_down</mat-icon>
        </button>

        <mat-menu #profileMenu="matMenu" xPosition="before" class="custom-profile-menu">
          <div class="menu-header">
            <p class="menu-user-name">{{ auth.user()?.name }}</p>
            <p class="menu-user-email">{{ auth.user()?.email }}</p>
          </div>
          <button mat-menu-item (click)="onProfileClick()">
            <mat-icon>person</mat-icon>
            <span>Profile</span>
          </button>
          <button mat-menu-item (click)="onSettingsClick()">
            <mat-icon>settings</mat-icon>
            <span>Settings</span>
          </button>
          <div class="menu-divider"></div>
          <button mat-menu-item (click)="signOut()" class="logout-item">
            <mat-icon>logout</mat-icon>
            <span>Sign Out</span>
          </button>
        </mat-menu>
      </div>
    </div>
  </header>

  <!-- MAIN CONTENT -->
  <main class="main-content">
    <div class="container-max">
      <!-- 1. Greeting -->
      <div class="greeting-section">
        <h1 class="greeting-title">
          {{ greeting }}, {{ firstName }}
        </h1>
        <p class="today-date">{{ todayFormatted }}</p>
      </div>

      <!-- 2. Action Buttons -->
      <div class="actions-row">
        <button mat-flat-button color="primary" (click)="onCreateForm()">
          <mat-icon>add</mat-icon>
          New Form
        </button>
        <button mat-stroked-button (click)="onCreateQuiz()">
          <mat-icon>dashboard_customize</mat-icon>
          New Quiz
        </button>
        <button mat-stroked-button (click)="onImport()">
          <mat-icon>cloud_upload</mat-icon>
          Quick import
        </button>
      </div>

      <!-- 3. Templates Section -->
      <section class="section-block">
        <h2 class="section-title">Explore templates</h2>
        <div class="templates-grid">
          @for (temp of TEMPLATES; track temp.title) {
            <button
              (click)="onTemplateClick(temp.title)"
              class="template-card"
              [style.background]="temp.gradient"
            >
              <div class="template-content">
                <p class="template-name">{{ temp.title }}</p>
                <p class="template-desc">{{ temp.desc }}</p>
              </div>
              <div class="template-circle-decor"></div>
            </button>
          }
        </div>
      </section>

      <!-- 4. Stats Summary -->
      <div class="stats-row">
        <!-- Card 1 -->
        <div class="stat-card">
          <div class="stat-header">
            <span class="stat-label">Total Forms</span>
            <div class="stat-icon-wrapper primary-tint">
              <mat-icon>description</mat-icon>
            </div>
          </div>
          <p class="stat-value">248</p>
        </div>
        <!-- Card 2 -->
        <div class="stat-card">
          <div class="stat-header">
            <span class="stat-label">Pending Approvals</span>
            <div class="stat-icon-wrapper warning-tint">
              <mat-icon>pending_actions</mat-icon>
            </div>
          </div>
          <p class="stat-value">12</p>
        </div>
        <!-- Card 3 -->
        <div class="stat-card">
          <div class="stat-header">
            <span class="stat-label">Submitted Today</span>
            <div class="stat-icon-wrapper success-tint">
              <mat-icon>check_circle</mat-icon>
            </div>
          </div>
          <p class="stat-value">34</p>
        </div>
        <!-- Card 4 -->
        <div class="stat-card">
          <div class="stat-header">
            <span class="stat-label">Active Workflows</span>
            <div class="stat-icon-wrapper accent-tint">
              <mat-icon>device_hub</mat-icon>
            </div>
          </div>
          <p class="stat-value">7</p>
        </div>
      </div>

      <!-- 5. Filtering + Search Bar -->
      <div class="filter-search-row">
        <!-- Tabs -->
        <div class="tabs-list">
          @for (tab of TABS; track tab) {
            <button
              (click)="onTabChange(tab)"
              class="tab-btn"
              [class.active]="activeTab() === tab"
            >
              @if (tab === 'Favorites') {
                <mat-icon class="tab-star-icon">star</mat-icon>
              }
              {{ tab }}
              @if (activeTab() === tab) {
                <span class="active-tab-indicator"></span>
              }
            </button>
          }
        </div>

        <!-- Controls -->
        <div class="controls-group">
          <!-- Search box -->
          <div class="search-box">
            <mat-icon class="search-icon">search</mat-icon>
            <input
              type="text"
              placeholder="Filter by keyword"
              [ngModel]="searchQuery()"
              (ngModelChange)="searchQuery.set($event)"
              class="search-input"
            />
          </div>

          <!-- View modes -->
          <button
            (click)="viewMode.set('list')"
            class="mode-btn"
            [class.active]="viewMode() === 'list'"
            aria-label="List view"
          >
            <mat-icon>view_list</mat-icon>
          </button>
          <button
            (click)="viewMode.set('grid')"
            class="mode-btn"
            [class.active]="viewMode() === 'grid'"
            aria-label="Grid view"
          >
            <mat-icon>grid_view</mat-icon>
          </button>
        </div>
      </div>

      <!-- 6. Forms Display -->
      <section class="forms-section">
        @if (viewMode() === 'grid') {
          <div class="forms-grid">
            @for (form of filteredForms; track form.id) {
              <button
                (click)="onFormClick(form.name)"
                class="form-grid-card"
              >
                <div class="form-thumbnail">
                  <mat-icon class="thumb-icon">insert_drive_file</mat-icon>
                  <span
                    class="status-indicator-dot"
                    [class.pending]="form.status === 'Pending'"
                    [class.approved]="form.status === 'Approved'"
                    [class.rejected]="form.status === 'Rejected'"
                  ></span>
                </div>
                <div class="form-card-details">
                  <p class="form-card-name">{{ form.name }}</p>
                  <p class="form-card-by">{{ form.by }}</p>
                  <div class="form-card-footer">
                    <span class="form-card-date">{{ form.date }}</span>
                    <span class="form-card-responses">{{ form.responses }} responses</span>
                  </div>
                </div>
              </button>
            }
          </div>
        } @else {
          <div class="table-container">
            <table class="data-table">
              <thead>
                <tr>
                  <th class="th-name">Form Name</th>
                  <th class="th-by">Submitted By</th>
                  <th class="th-date">Date</th>
                  <th class="th-status">Status</th>
                </tr>
              </thead>
              <tbody>
                @for (form of filteredForms; track form.id) {
                  <tr (click)="onFormClick(form.name)" class="table-row">
                    <td class="td-name font-medium">{{ form.name }}</td>
                    <td class="td-by">{{ form.by }}</td>
                    <td class="td-date">{{ form.date }}</td>
                    <td class="td-status">
                      <span
                        class="status-badge"
                        [class.pending]="form.status === 'Pending'"
                        [class.approved]="form.status === 'Approved'"
                        [class.rejected]="form.status === 'Rejected'"
                      >
                        {{ form.status }}
                      </span>
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        }
      </section>
    </div>
  </main>
</div>
