// src/routes/signin.tsx
import { createFileRoute, Link, Navigate, useNavigate } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { Eye, EyeOff, Lock, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { AuthLayout } from "@/components/auth-layout";
import { useAuth } from "@/lib/auth-context";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/signin")({
  head: () => ({ meta: [{ title: "Sign In — Jabil Forms" }] }),
  component: SignInPage,
});

function SignInPage() {
  const { signIn, isAuthenticated } = useAuth();
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPw, setShowPw] = useState(false);
  const [remember, setRemember] = useState(true);
  const [errors, setErrors] = useState<{ email?: string; password?: string }>({});
  const [shake, setShake] = useState(false);
  const [loading, setLoading] = useState(false);

  if (isAuthenticated) return <Navigate to="/dashboard" replace />;

  const validate = () => {
    const e: typeof errors = {};
    if (!email) e.email = "Email is required";
    else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) e.email = "Enter a valid email";
    if (!password) e.password = "Password is required";
    else if (password.length < 8) e.password = "Password must be at least 8 characters";
    return e;
  };

  const onSubmit = async (ev: FormEvent) => {
    ev.preventDefault();
    const e = validate();
    setErrors(e);
    if (Object.keys(e).length) {
      setShake(true);
      setTimeout(() => setShake(false), 450);
      return;
    }
    setLoading(true);
    try {
      await signIn(email, password);
      toast.success("Welcome back!");
      navigate({ to: "/dashboard" });
    } catch (err) {
      setShake(true);
      setTimeout(() => setShake(false), 450);
      toast.error(err instanceof Error ? err.message : "Sign in failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <AuthLayout>
      <div className={shake ? "animate-shake" : undefined}>
        <h2 className="text-3xl font-bold tracking-tight">Welcome back</h2>
        <p className="mt-1.5 text-sm text-muted-foreground">
          Sign in to your Jabil account
        </p>

        <form onSubmit={onSubmit} className="mt-7 space-y-4" noValidate>
          <Field
            label="Work Email"
            id="email"
            type="email"
            placeholder="you@jabil.com"
            value={email}
            onChange={setEmail}
            error={errors.email}
            autoComplete="email"
          />

          <PasswordField
            label="Password"
            id="password"
            value={password}
            onChange={setPassword}
            show={showPw}
            onToggle={() => setShowPw((s) => !s)}
            error={errors.password}
            autoComplete="current-password"
          />

          <div className="flex items-center justify-between text-sm">
            <label className="flex cursor-pointer items-center gap-2 text-foreground">
              <input
                type="checkbox"
                checked={remember}
                onChange={(e) => setRemember(e.target.checked)}
                className="h-4 w-4 rounded border-input accent-[var(--color-primary)]"
              />
              Remember me
            </label>
            <Link to="/forgot-password" className="font-medium text-primary hover:underline">
              Forgot password?
            </Link>
          </div>

          <Button type="submit" disabled={loading} className="h-12 w-full text-base">
            {loading ? <Loader2 className="animate-spin" /> : "Sign In"}
          </Button>
        </form>

        <div className="my-5 flex items-center gap-3 text-xs text-muted-foreground">
          <div className="h-px flex-1 bg-border" />
          or
          <div className="h-px flex-1 bg-border" />
        </div>

        <Button
          type="button"
          variant="outline"
          className="h-12 w-full text-base"
          onClick={() => toast.info("SSO is not configured in this demo")}
        >
          <Lock /> Continue with Jabil SSO
        </Button>

        <p className="mt-6 text-center text-sm text-muted-foreground">
          Don't have an account?{" "}
          <Link to="/signup" className="font-medium text-primary hover:underline">
            Create account
          </Link>
        </p>

        <p className="mt-4 rounded-md bg-secondary px-3 py-2 text-center text-xs text-muted-foreground">
          Demo: <span className="font-mono text-foreground">demo@jabil.com</span> /{" "}
          <span className="font-mono text-foreground">Jabil2025</span>
        </p>
      </div>
    </AuthLayout>
  );
}

export function Field({
  label,
  id,
  type = "text",
  value,
  onChange,
  error,
  placeholder,
  autoComplete,
}: {
  label: string;
  id: string;
  type?: string;
  value: string;
  onChange: (v: string) => void;
  error?: string;
  placeholder?: string;
  autoComplete?: string;
}) {
  return (
    <div>
      <label htmlFor={id} className="mb-1.5 block text-sm font-medium">
        {label}
      </label>
      <input
        id={id}
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        autoComplete={autoComplete}
        aria-invalid={!!error}
        aria-describedby={error ? `${id}-error` : undefined}
        className={`h-11 w-full rounded-md border bg-background px-3 text-sm outline-none transition-colors placeholder:text-muted-foreground/70 focus:border-primary focus:ring-2 focus:ring-primary/20 ${
          error ? "border-destructive" : "border-input"
        }`}
      />
      {error && (
        <p id={`${id}-error`} className="mt-1 text-xs text-destructive">
          {error}
        </p>
      )}
    </div>
  );
}

export function PasswordField({
  label,
  id,
  value,
  onChange,
  show,
  onToggle,
  error,
  autoComplete,
}: {
  label: string;
  id: string;
  value: string;
  onChange: (v: string) => void;
  show: boolean;
  onToggle: () => void;
  error?: string;
  autoComplete?: string;
}) {
  return (
    <div>
      <label htmlFor={id} className="mb-1.5 block text-sm font-medium">
        {label}
      </label>
      <div className="relative">
        <input
          id={id}
          type={show ? "text" : "password"}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          autoComplete={autoComplete}
          aria-invalid={!!error}
          aria-describedby={error ? `${id}-error` : undefined}
          className={`h-11 w-full rounded-md border bg-background px-3 pr-11 text-sm outline-none transition-colors focus:border-primary focus:ring-2 focus:ring-primary/20 ${
            error ? "border-destructive" : "border-input"
          }`}
        />
        <button
          type="button"
          onClick={onToggle}
          aria-label={show ? "Hide password" : "Show password"}
          className="absolute right-2 top-1/2 -translate-y-1/2 rounded p-1.5 text-muted-foreground hover:text-foreground"
        >
          {show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
        </button>
      </div>
      {error && (
        <p id={`${id}-error`} className="mt-1 text-xs text-destructive">
          {error}
        </p>
      )}
    </div>
  );
}

// frontend/src/app/pages/signin/signin.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-signin',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterLink,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatCheckboxModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
  ],
  templateUrl: './signin.component.html',
  styleUrl: './signin.component.scss',
})
export class SigninComponent {
  email = '';
  password = '';
  showPassword = false;
  remember = true;
  loading = signal(false);
  shake = signal(false);
  errors = signal<{ email?: string; password?: string }>({});

  constructor(
    private auth: AuthService,
    private router: Router,
    private snackBar: MatSnackBar
  ) {}

  togglePassword(): void {
    this.showPassword = !this.showPassword;
  }

  async onSubmit(): Promise<void> {
    const errs: { email?: string; password?: string } = {};

    if (!this.email) {
      errs.email = 'Email is required';
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.email)) {
      errs.email = 'Enter a valid email';
    }

    if (!this.password) {
      errs.password = 'Password is required';
    } else if (this.password.length < 8) {
      errs.password = 'Password must be at least 8 characters';
    }

    this.errors.set(errs);

    if (Object.keys(errs).length) {
      this.triggerShake();
      return;
    }

    this.loading.set(true);
    try {
      await this.auth.signIn(this.email, this.password);
      this.snackBar.open('Welcome back!', 'Close', { duration: 3000 });
      this.router.navigate(['/dashboard']);
    } catch (err) {
      this.triggerShake();
      const message = err instanceof Error ? err.message : 'Sign in failed';
      this.snackBar.open(message, 'Close', { duration: 5000 });
    } finally {
      this.loading.set(false);
    }
  }

  onSsoClick(): void {
    this.snackBar.open('SSO is not configured in this demo', 'Close', { duration: 3000 });
  }

  private triggerShake(): void {
    this.shake.set(true);
    setTimeout(() => this.shake.set(false), 450);
  }
}

<div [class.animate-shake]="shake()">
  <h2 class="auth-title">Welcome back</h2>
  <p class="auth-subtitle">Sign in to your Jabil account</p>

  <form (ngSubmit)="onSubmit()" class="auth-form" novalidate>
    <!-- Email -->
    <mat-form-field appearance="outline" class="full-width">
      <mat-label>Work Email</mat-label>
      <input
        matInput
        type="email"
        [(ngModel)]="email"
        name="email"
        placeholder="you@jabil.com"
        autocomplete="email"
      />
      @if (errors().email) {
        <mat-error>{{ errors().email }}</mat-error>
      }
    </mat-form-field>

    <!-- Password -->
    <mat-form-field appearance="outline" class="full-width">
      <mat-label>Password</mat-label>
      <input
        matInput
        [type]="showPassword ? 'text' : 'password'"
        [(ngModel)]="password"
        name="password"
        autocomplete="current-password"
      />
      <button
        mat-icon-button
        matSuffix
        type="button"
        (click)="togglePassword()"
        [attr.aria-label]="showPassword ? 'Hide password' : 'Show password'"
      >
        <mat-icon>{{ showPassword ? 'visibility_off' : 'visibility' }}</mat-icon>
      </button>
      @if (errors().password) {
        <mat-error>{{ errors().password }}</mat-error>
      }
    </mat-form-field>

    <!-- Remember + Forgot -->
    <div class="form-row">
      <mat-checkbox [(ngModel)]="remember" name="remember" color="primary">
        Remember me
      </mat-checkbox>
      <a routerLink="/forgot-password" class="forgot-link">Forgot password?</a>
    </div>

    <!-- Submit -->
    <button
      mat-flat-button
      color="primary"
      type="submit"
      class="submit-btn"
      [disabled]="loading()"
    >
      @if (loading()) {
        <mat-spinner diameter="20" color="accent"></mat-spinner>
      } @else {
        Sign In
      }
    </button>
  </form>

  <!-- Divider -->
  <div class="divider">
    <span class="divider-line"></span>
    <span class="divider-text">or</span>
    <span class="divider-line"></span>
  </div>

  <!-- SSO -->
  <button
    mat-stroked-button
    class="sso-btn"
    type="button"
    (click)="onSsoClick()"
  >
    <mat-icon>lock</mat-icon>
    Continue with Jabil SSO
  </button>

  <!-- Sign Up Link -->
  <p class="switch-link">
    Don't have an account?
    <a routerLink="/signup" class="link-primary">Create account</a>
  </p>

  <!-- Demo hint -->
  <div class="demo-hint">
    Demo: <code>demo&#64;jabil.com</code> / <code>Jabil2025</code>
  </div>
</div>
