// frontend/src/app/pages/forgot-password/forgot-password.component.ts
import { Component, signal, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';

@Component({
  selector: 'app-forgot-password',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterLink,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
  ],
  templateUrl: './forgot-password.component.html',
  styleUrl: './forgot-password.component.scss',
})
export class ForgotPasswordComponent implements OnDestroy {
  email = '';
  error = signal<string | null>(null);
  loading = signal(false);
  shake = signal(false);
  sentTo = signal<string | null>(null);
  cooldown = signal(0);
  private timer: any;

  constructor(private snackBar: MatSnackBar) {}

  async onSubmit(): Promise<void> {
    if (!this.email) {
      this.error.set('Email is required');
      this.triggerShake();
      return;
    }

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.email)) {
      this.error.set('Enter a valid email');
      this.triggerShake();
      return;
    }

    this.error.set(null);
    this.loading.set(true);

    try {
      await new Promise((r) => setTimeout(r, 600));
      this.sentTo.set(this.email);
      this.startCooldown(30);
    } catch {
      this.triggerShake();
      this.snackBar.open('Failed to send reset link', 'Close', { duration: 5000 });
    } finally {
      this.loading.set(false);
    }
  }

  resend(): void {
    if (this.cooldown() > 0) return;
    this.snackBar.open('Reset link sent again', 'Close', { duration: 3000 });
    this.startCooldown(30);
  }

  private startCooldown(seconds: number): void {
    this.cooldown.set(seconds);
    if (this.timer) {
      clearInterval(this.timer);
    }
    this.timer = setInterval(() => {
      const current = this.cooldown();
      if (current <= 1) {
        this.cooldown.set(0);
        clearInterval(this.timer);
      } else {
        this.cooldown.set(current - 1);
      }
    }, 1000);
  }

  private triggerShake(): void {
    this.shake.set(true);
    setTimeout(() => this.shake.set(false), 450);
  }

  ngOnDestroy(): void {
    if (this.timer) {
      clearInterval(this.timer);
    }
  }
}

@if (!sentTo()) {
  <div [class.animate-shake]="shake()">
    <h2 class="auth-title">Reset your password</h2>
    <p class="auth-subtitle">
      Enter your work email and we'll send you a reset link.
    </p>

    <form (ngSubmit)="onSubmit()" class="auth-form" novalidate>
      <!-- Email -->
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Work Email</mat-label>
        <input
          matInput
          type="email"
          [(ngModel)]="email"
          name="email"
          placeholder="you@jabil.com"
          autocomplete="email"
        />
        @if (error()) {
          <mat-error>{{ error() }}</mat-error>
        }
      </mat-form-field>

      <!-- Submit -->
      <button
        mat-flat-button
        color="primary"
        type="submit"
        class="submit-btn"
        [disabled]="loading()"
      >
        @if (loading()) {
          <mat-spinner diameter="20" color="accent"></mat-spinner>
        } @else {
          Send Reset Link
        }
      </button>
    </form>

    <p class="back-link">
      <a routerLink="/signin" class="link-primary inline-flex">
        <mat-icon class="back-icon">arrow_back</mat-icon>
        Back to Sign In
      </a>
    </p>
  </div>
} @else {
  <div class="sent-view animate-fade-in">
    <div class="mail-icon-container">
      <mat-icon class="mail-icon">mark_email_read</mat-icon>
    </div>
    <h2 class="auth-title mt-5">Check your inbox</h2>
    <p class="auth-subtitle mt-2">
      We sent a password reset link to <span class="highlight-email">{{ sentTo() }}</span>.
      Check your spam folder if you don't see it.
    </p>

    <button
      mat-button
      color="primary"
      class="resend-btn"
      (click)="resend()"
      [disabled]="cooldown() > 0"
    >
      @if (cooldown() > 0) {
        Resend email in {{ cooldown() }}s
      } @else {
        Resend email
      }
    </button>

    <div class="back-link-divider">
      <a routerLink="/signin" class="link-primary inline-flex">
        <mat-icon class="back-icon">arrow_back</mat-icon>
        Back to Sign In
      </a>
    </div>
  </div>
}

// src/routes/forgot-password.tsx
import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, Loader2, MailCheck } from "lucide-react";
import { AuthLayout } from "@/components/auth-layout";
import { Button } from "@/components/ui/button";
import { Field } from "./signin";
import { toast } from "sonner";

export const Route = createFileRoute("/forgot-password")({
  head: () => ({ meta: [{ title: "Reset Password — Jabil Forms" }] }),
  component: ForgotPasswordPage,
});

function ForgotPasswordPage() {
  const [email, setEmail] = useState("");
  const [error, setError] = useState<string | undefined>();
  const [shake, setShake] = useState(false);
  const [loading, setLoading] = useState(false);
  const [sentTo, setSentTo] = useState<string | null>(null);
  const [cooldown, setCooldown] = useState(0);

  useEffect(() => {
    if (cooldown <= 0) return;
    const t = setTimeout(() => setCooldown((c) => c - 1), 1000);
    return () => clearTimeout(t);
  }, [cooldown]);

  const submit = async (ev: FormEvent) => {
    ev.preventDefault();
    if (!email) {
      setError("Email is required");
      setShake(true); setTimeout(() => setShake(false), 450);
      return;
    }
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      setError("Enter a valid email");
      setShake(true); setTimeout(() => setShake(false), 450);
      return;
    }
    setError(undefined);
    setLoading(true);
    await new Promise((r) => setTimeout(r, 600));
    setSentTo(email);
    setCooldown(30);
    setLoading(false);
  };

  const resend = () => {
    if (cooldown > 0) return;
    toast.success("Reset link sent again");
    setCooldown(30);
  };

  return (
    <AuthLayout>
      {!sentTo ? (
        <div className={shake ? "animate-shake" : undefined}>
          <h2 className="text-3xl font-bold tracking-tight">Reset your password</h2>
          <p className="mt-1.5 text-sm text-muted-foreground">
            Enter your work email and we'll send you a reset link.
          </p>
          <form onSubmit={submit} className="mt-7 space-y-4" noValidate>
            <Field
              label="Work Email"
              id="email"
              type="email"
              placeholder="you@jabil.com"
              value={email}
              onChange={setEmail}
              error={error}
              autoComplete="email"
            />
            <Button type="submit" disabled={loading} className="h-12 w-full text-base">
              {loading ? <Loader2 className="animate-spin" /> : "Send Reset Link"}
            </Button>
          </form>
          <p className="mt-6 text-center text-sm">
            <Link to="/signin" className="inline-flex items-center gap-1 font-medium text-primary hover:underline">
              <ArrowLeft className="h-4 w-4" /> Back to Sign In
            </Link>
          </p>
        </div>
      ) : (
        <div className="animate-fade-in text-center">
          <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-primary/10">
            <MailCheck className="h-8 w-8 text-primary" />
          </div>
          <h2 className="mt-5 text-2xl font-bold tracking-tight">Check your inbox</h2>
          <p className="mt-2 text-sm text-muted-foreground">
            We sent a password reset link to{" "}
            <span className="font-medium text-foreground">{sentTo}</span>. Check your spam folder if you don't see it.
          </p>
          <button
            onClick={resend}
            disabled={cooldown > 0}
            className="mt-5 text-sm font-medium text-primary hover:underline disabled:cursor-not-allowed disabled:text-muted-foreground disabled:no-underline"
          >
            {cooldown > 0 ? `Resend email in ${cooldown}s` : "Resend email"}
          </button>
          <div className="mt-6 border-t border-border pt-5">
            <Link to="/signin" className="inline-flex items-center gap-1 text-sm font-medium text-primary hover:underline">
              <ArrowLeft className="h-4 w-4" /> Back to Sign In
            </Link>
          </div>
        </div>
      )}
    </AuthLayout>
  );
}
