// src/routes/signup.tsx
import { createFileRoute, Link, Navigate, useNavigate } from "@tanstack/react-router";
import { useMemo, useState, type FormEvent } from "react";
import { Loader2 } from "lucide-react";
import { toast } from "sonner";
import { AuthLayout } from "@/components/auth-layout";
import { useAuth } from "@/lib/auth-context";
import { Button } from "@/components/ui/button";
import { Field, PasswordField } from "./signin";

export const Route = createFileRoute("/signup")({
  head: () => ({ meta: [{ title: "Create Account — Jabil Forms" }] }),
  component: SignUpPage,
});

const DEPARTMENTS = [
  "Manufacturing",
  "Quality",
  "Engineering",
  "Logistics",
  "Finance",
  "HR",
  "IT",
  "Other",
];

function passwordStrength(pw: string): { label: string; score: 0 | 1 | 2 | 3; color: string } {
  let score = 0;
  if (pw.length >= 8) score++;
  if (/[A-Z]/.test(pw)) score++;
  if (/\d/.test(pw)) score++;
  if (/[^A-Za-z0-9]/.test(pw)) score++;
  if (score <= 1) return { label: "Weak", score: 1, color: "bg-destructive" };
  if (score === 2 || score === 3) return { label: "Fair", score: 2, color: "bg-amber-500" };
  return { label: "Strong", score: 3, color: "bg-success" };
}

function SignUpPage() {
  const { signUp, isAuthenticated } = useAuth();
  const navigate = useNavigate();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [department, setDepartment] = useState("");
  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [showPw, setShowPw] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [agree, setAgree] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [shake, setShake] = useState(false);
  const [loading, setLoading] = useState(false);

  const strength = useMemo(() => passwordStrength(password), [password]);

  if (isAuthenticated) return <Navigate to="/dashboard" replace />;

  const validate = () => {
    const e: Record<string, string> = {};
    if (!name.trim()) e.name = "Full name is required";
    if (!email) e.email = "Email is required";
    else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) e.email = "Enter a valid email";
    if (!department) e.department = "Select a department";
    if (!password) e.password = "Password is required";
    else if (password.length < 8) e.password = "At least 8 characters";
    else if (!/[A-Z]/.test(password)) e.password = "Must include 1 uppercase letter";
    else if (!/\d/.test(password)) e.password = "Must include 1 number";
    if (!confirm) e.confirm = "Confirm your password";
    else if (confirm !== password) e.confirm = "Passwords do not match";
    return e;
  };

  const onSubmit = async (ev: FormEvent) => {
    ev.preventDefault();
    const e = validate();
    setErrors(e);
    if (Object.keys(e).length) {
      setShake(true);
      setTimeout(() => setShake(false), 450);
      return;
    }
    setLoading(true);
    try {
      await signUp(name, email);
      toast.success("Account created. Welcome to Jabil Forms!");
      navigate({ to: "/dashboard" });
    } finally {
      setLoading(false);
    }
  };

  return (
    <AuthLayout>
      <div className={shake ? "animate-shake" : undefined}>
        <h2 className="text-3xl font-bold tracking-tight">Create your account</h2>
        <p className="mt-1.5 text-sm text-muted-foreground">
          Join your Jabil team on Jabil Forms
        </p>

        <form onSubmit={onSubmit} className="mt-6 space-y-4" noValidate>
          <Field label="Full Name" id="name" value={name} onChange={setName}
            placeholder="Jane Smith" error={errors.name} autoComplete="name" />
          <Field label="Work Email" id="email" type="email" value={email} onChange={setEmail}
            placeholder="you@jabil.com" error={errors.email} autoComplete="email" />

          <div>
            <label htmlFor="department" className="mb-1.5 block text-sm font-medium">
              Department
            </label>
            <select
              id="department"
              value={department}
              onChange={(e) => setDepartment(e.target.value)}
              aria-invalid={!!errors.department}
              aria-describedby={errors.department ? "department-error" : undefined}
              className={`h-11 w-full rounded-md border bg-background px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20 ${
                errors.department ? "border-destructive" : "border-input"
              }`}
            >
              <option value="">Select department…</option>
              {DEPARTMENTS.map((d) => (
                <option key={d} value={d}>{d}</option>
              ))}
            </select>
            {errors.department && (
              <p id="department-error" className="mt-1 text-xs text-destructive">{errors.department}</p>
            )}
          </div>

          <div>
            <PasswordField label="Password" id="password" value={password} onChange={setPassword}
              show={showPw} onToggle={() => setShowPw((s) => !s)} error={errors.password}
              autoComplete="new-password" />
            {password && (
              <div className="mt-2">
                <div className="flex gap-1">
                  {[1, 2, 3].map((i) => (
                    <div
                      key={i}
                      className={`h-1.5 flex-1 rounded-full transition-colors ${
                        i <= strength.score ? strength.color : "bg-border"
                      }`}
                    />
                  ))}
                </div>
                <p className="mt-1 text-xs text-muted-foreground">
                  Strength: <span className="font-medium text-foreground">{strength.label}</span>
                </p>
              </div>
            )}
          </div>

          <PasswordField label="Confirm Password" id="confirm" value={confirm} onChange={setConfirm}
            show={showConfirm} onToggle={() => setShowConfirm((s) => !s)} error={errors.confirm}
            autoComplete="new-password" />

          <label className="flex cursor-pointer items-start gap-2.5 text-sm">
            <input
              type="checkbox"
              checked={agree}
              onChange={(e) => setAgree(e.target.checked)}
              className="mt-0.5 h-4 w-4 rounded border-input accent-[var(--color-primary)]"
            />
            <span className="text-muted-foreground">
              I agree to the{" "}
              <a href="#" target="_blank" rel="noreferrer" className="font-medium text-primary hover:underline">Terms of Service</a>{" "}
              and{" "}
              <a href="#" target="_blank" rel="noreferrer" className="font-medium text-primary hover:underline">Privacy Policy</a>
            </span>
          </label>

          <Button type="submit" disabled={!agree || loading} className="h-12 w-full text-base">
            {loading ? <Loader2 className="animate-spin" /> : "Create Account"}
          </Button>
        </form>

        <p className="mt-6 text-center text-sm text-muted-foreground">
          Already have an account?{" "}
          <Link to="/signin" className="font-medium text-primary hover:underline">Sign In</Link>
        </p>
      </div>
    </AuthLayout>
  );
}

// frontend/src/app/pages/signup/signup.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatSelectModule } from '@angular/material/select';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-signup',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterLink,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatSelectModule,
    MatCheckboxModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
  ],
  templateUrl: './signup.component.html',
  styleUrl: './signup.component.scss',
})
export class SignupComponent {
  name = '';
  email = '';
  department = '';
  password = '';
  confirm = '';
  showPassword = false;
  showConfirm = false;
  agree = false;
  loading = signal(false);
  shake = signal(false);
  errors = signal<{
    name?: string;
    email?: string;
    department?: string;
    password?: string;
    confirm?: string;
  }>({});

  readonly DEPARTMENTS = [
    'Manufacturing',
    'Quality',
    'Engineering',
    'Logistics',
    'Finance',
    'HR',
    'IT',
    'Other',
  ];

  constructor(
    private auth: AuthService,
    private router: Router,
    private snackBar: MatSnackBar
  ) {}

  togglePassword(): void {
    this.showPassword = !this.showPassword;
  }

  toggleConfirm(): void {
    this.showConfirm = !this.showConfirm;
  }

  get strength() {
    const pw = this.password;
    if (!pw) return { label: '', score: 0, colorClass: '' };
    let score = 0;
    if (pw.length >= 8) score++;
    if (/[A-Z]/.test(pw)) score++;
    if (/\d/.test(pw)) score++;
    if (/[^A-Za-z0-9]/.test(pw)) score++;

    if (score <= 1) return { label: 'Weak', score: 1, colorClass: 'weak' };
    if (score === 2 || score === 3) return { label: 'Fair', score: 2, colorClass: 'fair' };
    return { label: 'Strong', score: 3, colorClass: 'strong' };
  }

  async onSubmit(): Promise<void> {
    const errs: {
      name?: string;
      email?: string;
      department?: string;
      password?: string;
      confirm?: string;
    } = {};

    if (!this.name.trim()) {
      errs.name = 'Full name is required';
    }

    if (!this.email) {
      errs.email = 'Email is required';
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.email)) {
      errs.email = 'Enter a valid email';
    }

    if (!this.department) {
      errs.department = 'Select a department';
    }

    if (!this.password) {
      errs.password = 'Password is required';
    } else if (this.password.length < 8) {
      errs.password = 'Password must be at least 8 characters';
    } else if (!/[A-Z]/.test(this.password)) {
      errs.password = 'Must include 1 uppercase letter';
    } else if (!/\d/.test(this.password)) {
      errs.password = 'Must include 1 number';
    }

    if (!this.confirm) {
      errs.confirm = 'Confirm your password';
    } else if (this.confirm !== this.password) {
      errs.confirm = 'Passwords do not match';
    }

    this.errors.set(errs);

    if (Object.keys(errs).length) {
      this.triggerShake();
      return;
    }

    if (!this.agree) {
      return;
    }

    this.loading.set(true);
    try {
      await this.auth.signUp(this.name, this.email);
      this.snackBar.open('Account created. Welcome to Jabil Forms!', 'Close', { duration: 3000 });
      this.router.navigate(['/dashboard']);
    } catch (err) {
      this.triggerShake();
      const message = err instanceof Error ? err.message : 'Sign up failed';
      this.snackBar.open(message, 'Close', { duration: 5000 });
    } finally {
      this.loading.set(false);
    }
  }

  private triggerShake(): void {
    this.shake.set(true);
    setTimeout(() => this.shake.set(false), 450);
  }
}

<div [class.animate-shake]="shake()">
  <h2 class="auth-title">Create your account</h2>
  <p class="auth-subtitle">Join your Jabil team on Jabil Forms</p>

  <form (ngSubmit)="onSubmit()" class="auth-form" novalidate>
    <!-- Full Name -->
    <mat-form-field appearance="outline" class="full-width">
      <mat-label>Full Name</mat-label>
      <input
        matInput
        type="text"
        [(ngModel)]="name"
        name="name"
        placeholder="Jane Smith"
        autocomplete="name"
      />
      @if (errors().name) {
        <mat-error>{{ errors().name }}</mat-error>
      }
    </mat-form-field>

    <!-- Email -->
    <mat-form-field appearance="outline" class="full-width">
      <mat-label>Work Email</mat-label>
      <input
        matInput
        type="email"
        [(ngModel)]="email"
        name="email"
        placeholder="you@jabil.com"
        autocomplete="email"
      />
      @if (errors().email) {
        <mat-error>{{ errors().email }}</mat-error>
      }
    </mat-form-field>

    <!-- Department -->
    <mat-form-field appearance="outline" class="full-width">
      <mat-label>Department</mat-label>
      <mat-select [(ngModel)]="department" name="department">
        <mat-option value="">Select department...</mat-option>
        @for (dept of DEPARTMENTS; track dept) {
          <mat-option [value]="dept">{{ dept }}</mat-option>
        }
      </mat-select>
      @if (errors().department) {
        <mat-error>{{ errors().department }}</mat-error>
      }
    </mat-form-field>

    <!-- Password -->
    <mat-form-field appearance="outline" class="full-width">
      <mat-label>Password</mat-label>
      <input
        matInput
        [type]="showPassword ? 'text' : 'password'"
        [(ngModel)]="password"
        name="password"
        autocomplete="new-password"
      />
      <button
        mat-icon-button
        matSuffix
        type="button"
        (click)="togglePassword()"
        [attr.aria-label]="showPassword ? 'Hide password' : 'Show password'"
      >
        <mat-icon>{{ showPassword ? 'visibility_off' : 'visibility' }}</mat-icon>
      </button>
      @if (errors().password) {
        <mat-error>{{ errors().password }}</mat-error>
      }
    </mat-form-field>

    <!-- Password Strength Indicator -->
    @if (password) {
      <div class="strength-indicator">
        <div class="strength-bars">
          <div
            class="strength-bar"
            [class.active]="strength.score >= 1"
            [class.weak]="strength.score === 1"
            [class.fair]="strength.score === 2"
            [class.strong]="strength.score === 3"
          ></div>
          <div
            class="strength-bar"
            [class.active]="strength.score >= 2"
            [class.fair]="strength.score === 2"
            [class.strong]="strength.score === 3"
          ></div>
          <div
            class="strength-bar"
            [class.active]="strength.score >= 3"
            [class.strong]="strength.score === 3"
          ></div>
        </div>
        <p class="strength-text">
          Strength: <span class="strength-label" [ngClass]="strength.colorClass">{{ strength.label }}</span>
        </p>
      </div>
    }

    <!-- Confirm Password -->
    <mat-form-field appearance="outline" class="full-width">
      <mat-label>Confirm Password</mat-label>
      <input
        matInput
        [type]="showConfirm ? 'text' : 'password'"
        [(ngModel)]="confirm"
        name="confirm"
        autocomplete="new-password"
      />
      <button
        mat-icon-button
        matSuffix
        type="button"
        (click)="toggleConfirm()"
        [attr.aria-label]="showConfirm ? 'Hide password' : 'Show password'"
      >
        <mat-icon>{{ showConfirm ? 'visibility_off' : 'visibility' }}</mat-icon>
      </button>
      @if (errors().confirm) {
        <mat-error>{{ errors().confirm }}</mat-error>
      }
    </mat-form-field>

    <!-- Agree Checkbox -->
    <div class="checkbox-row">
      <mat-checkbox [(ngModel)]="agree" name="agree" color="primary">
        <span class="terms-text">
          I agree to the
          <a href="#" target="_blank" rel="noreferrer" class="link-inline">Terms of Service</a>
          and
          <a href="#" target="_blank" rel="noreferrer" class="link-inline">Privacy Policy</a>
        </span>
      </mat-checkbox>
    </div>

    <!-- Submit Button -->
    <button
      mat-flat-button
      color="primary"
      type="submit"
      class="submit-btn"
      [disabled]="!agree || loading()"
    >
      @if (loading()) {
        <mat-spinner diameter="20" color="accent"></mat-spinner>
      } @else {
        Create Account
      }
    </button>
  </form>

  <!-- Sign In Link -->
  <p class="switch-link">
    Already have an account?
    <a routerLink="/signin" class="link-primary">Sign In</a>
  </p>
</div>
